export const ROUTES = {
  LOGIN: "/login",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/reset-password",
  FORBIDDEN: "/403",
  DASHBOARD: "/dashboard",
  QUOTES: "/quotes",
  NEW_QUOTE: "/quotes/new",
  QUOTE: (id: string) => `/quotes/${id}`,
  QUOTE_PREVIEW: (id: string) => `/quotes/${id}/preview`,
  TEMPLATES: "/templates",
  ADMIN_SETTINGS: "/admin/settings",
  ADMIN_CATALOG: "/admin/catalog",
  ADMIN_DISCOUNT_RULES: "/admin/discount-rules",
  ADMIN_USERS: "/admin/users",
  MANAGER_DASHBOARD: "/manager/dashboard",
  MANAGER_APPROVALS: "/manager/approvals",
  MANAGER_APPROVAL_DETAIL: (id: string) => `/manager/approvals/${id}`,
  MANAGER_ANALYTICS: "/manager/analytics",
} as const
